### ISSUE TITLE
Incompatible with libvcs 0.12

### ISSUE THREAD

**Issue by mauritsvanrees** [bluedynamics/mxdev#10]
In the `plone.scale` repo we use `mxdev`. This currently works on Python 3.8 and lower, but fails on 3.9 and 3.10 because pip then pulls in a newer `libvcs` which fails for us:

```
$ tox -e plone60-py39
plone60-py39 create: /Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py39
plone60-py39 run-test-pre: PYTHONHASHSEED='3997488647'
plone60-py39 run-test-pre: commands[0] | pip install mxdev
Collecting mxdev
  Using cached mxdev-2.0.0-py3-none-any.whl (8.6 kB)
Requirement already satisfied: setuptools in ./.tox/plone60-py39/lib/python3.9/site-packages (from mxdev) (62.0.0)
Collecting libvcs>=0.10.1
  Using cached libvcs-0.12.0-py3-none-any.whl (34 kB)
Installing collected packages: libvcs, mxdev
Successfully installed libvcs-0.12.0 mxdev-2.0.0
plone60-py39 run-test-pre: commands[1] | mxdev -c sources-60.ini
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py39/bin/mxdev", line 5, in <module>
    from mxdev import main
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py39/lib/python3.9/site-packages/mxdev.py", line 2, in <module>
    from libvcs.shortcuts import create_repo_from_pip_url
ImportError: cannot import name 'create_repo_from_pip_url' from 'libvcs.shortcuts' (/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py39/lib/python3.9/site-packages/libvcs/shortcuts.py)
ERROR: InvocationError for command /Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py39/bin/mxdev -c sources-60.ini (exited with code 1)
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
ERROR:   plone60-py39: commands failed
```

I have a fix ready. Not sure how to try that out, but I will make a PR.
